const $=id=>document.getElementById(id);
const limits=[5,4,5,3,10],bitWidths=[4,4,5,4,6],names=['SCOUT ALIEN','RAIDER ALIEN','COMMANDER ALIEN','ELITE ALIEN','BOSS: OVERLORD'];
let round=1,health=5,hits=0,value=0,choices=[],deadline=0,active=false,locked=true,raf=0,nextTimer=0,deck=[],last=-1,sound=false,audio;
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function beep(ok){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='square';o.frequency.setValueAtTime(ok?220:100,audio.currentTime);o.frequency.exponentialRampToValueAtTime(ok?90:40,audio.currentTime+.15);g.gain.setValueAtTime(.07,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.2)}catch{}}
function cancel(){cancelAnimationFrame(raf);clearTimeout(nextTimer);active=false;locked=true}
function hud(){ $('round').textContent=round===5?'ROUND 5 · BOSS':`ROUND ${round}`;$('mode').textContent=`${bitWidths[Math.min(round,5)-1]} BITS · ${limits[round-1]} SECONDS`;$('player').value=health;$('alien').value=10-hits;$('playerText').textContent=`${health} / 5`;$('alienText').textContent=`${10-hits} / 10`;$('alienName').textContent=names[round-1];$('arena').classList.toggle('boss',round===5)}
function showOverlay(title,text,button,overline){$('overlay').hidden=false;$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('start').textContent=button;$('overline').textContent=overline;$('rules').hidden=true}
function setupRound(){cancel();health=5;hits=0;deck=[];last=-1;hud();showOverlay(round===5?'THE OVERLORD HAS ARRIVED!':`ROUND ${round}: ${names[round-1]}`,`Decode ${bitWidths[round-1]}-bit binary numbers from 0–${2**bitWidths[round-1]-1}. Land ten punches. You have ${limits[round-1]} seconds per answer.${round>=4?' Place-value labels are hidden.':''}`,`Fight ${round===5?'the boss':`round ${round}`}`,round===5?'FINAL DEFENCE OF NEW ZEALAND':'KEEP THE ALIENS BACK!')}
function start(){if(health<=0||round>5){round=1;health=5;hits=0;deck=[];last=-1}cancel();active=true;$('overlay').hidden=true;hud();question()}
function question(){if(!active)return;locked=false;const width=bitWidths[Math.min(round,5)-1],max=2**width-1;if(!deck.length)deck=shuffle(Array.from({length:max+1},(_,i)=>i));value=deck.pop();if(value===last&&deck.length){const other=deck.pop();deck.unshift(value);value=other}last=value;const set=new Set([value]);if(round===5){const bitFlip=value^(1<<Math.floor(Math.random()*width));set.add(bitFlip)}while(set.size<4)set.add(Math.floor(Math.random()*(max+1)));choices=shuffle([...set]);const bin=value.toString(2).padStart(width,'0');$('bits').innerHTML=bin.split('').map((b,i)=>`<div class="bit">${round<4?`<div class="place">${2**(width-1-i)}</div>`:''}<div class="digit ${b==='1'?'on':''}">${b}</div></div>`).join('');$('answers').replaceChildren();choices.forEach((n,i)=>{const b=document.createElement('button');b.textContent=n;b.setAttribute('aria-label',`Answer ${n}, key ${i+1}`);b.onclick=()=>answer(n);$('answers').append(b)});$('feedback').textContent='Tap the decimal value. Land a punch!';$('impact').textContent='';$('arena').classList.remove('punch','zap');deadline=performance.now()+limits[round-1]*1000;tick()}
function tick(){if(!active||locked)return;const left=Math.max(0,deadline-performance.now());$('time').textContent=`${(left/1000).toFixed(1)} s`;$('timefill').style.width=`${left/(limits[round-1]*1000)*100}%`;if(left<=0){answer(null);return}raf=requestAnimationFrame(tick)}
function explanation(){const width=bitWidths[Math.min(round,5)-1],parts=[];for(let i=width-1;i>=0;i--)if(value&(1<<i))parts.push(2**i);return `${value.toString(2).padStart(width,'0')} = ${parts.length?parts.join(' + '):'0'}${parts.length>1?` = ${value}`:''}`}
function answer(n){if(!active||locked)return;if(performance.now()>=deadline)n=null;locked=true;cancelAnimationFrame(raf);const ok=n===value;[...$('answers').children].forEach(b=>{b.disabled=true;if(Number(b.textContent)===value)b.classList.add('correct');else if(Number(b.textContent)===n)b.classList.add('wrong')});if(ok)hits++;else health--;$('arena').classList.add(ok?'punch':'zap');$('impact').textContent=ok?'POW!':'ZAP!';$('feedback').textContent=`${ok?'Correct!':n===null?'Time up!':'Wrong answer!'} ${explanation()}`;beep(ok);hud();nextTimer=setTimeout(()=>{if(health<=0){cancel();showOverlay('YOU WERE ZAPPED OUT!',`You reached round ${round}. New Zealand needs another hero. Try again from round 1.`,'Try again · round 1','GAME OVER');return}if(hits>=10){if(round===5){cancel();round=6;showOverlay('NEW ZEALAND IS SAVED!','You defeated the Overlord with ten six-bit punches. Binary boxing champion!','Play again · round 1','VICTORY');return}round++;setupRound();return}question()},ok?650:1600)}
$('start').onclick=start;$('restart').onclick=()=>{round=1;setupRound()};$('sound').onclick=()=>{sound=!sound;$('sound').textContent=`Sound: ${sound?'on':'off'}`;$('sound').setAttribute('aria-pressed',sound);if(sound)beep(true)};document.addEventListener('keydown',e=>{if(e.repeat||e.ctrlKey||e.altKey||e.metaKey)return;if(['1','2','3','4'].includes(e.key)&&active&&!locked){e.preventDefault();answer(choices[Number(e.key)-1])}});
function gameState(){return {round,health,alienHealth:10-hits,active,binary:value.toString(2).padStart(bitWidths[Math.min(round,5)-1],'0'),choices:[...choices]}}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_binary_boxing_state',description:'Read the current round, life bars, binary question and answer options.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>gameState()})).catch(()=>{})}catch{}}
// Expose the same state and actions for local verification.
window.binaryBoxing={state:gameState,start,answer,restart:()=>{round=1;setupRound()}};hud();

const introTimers=[];const intro=$('intro');const startButton=$('start');startButton.disabled=true;$('skipIntro').focus();function finishIntro(){introTimers.forEach(clearTimeout);intro.hidden=true;startButton.disabled=false;startButton.focus()}$('skipIntro').onclick=finishIntro;intro.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();finishIntro()}else if(e.key==='Tab'){e.preventDefault();$('skipIntro').focus()}});introTimers.push(setTimeout(()=>{$('introTitle').textContent='THE ALIENS HAVE LANDED!';$('introLine').textContent='Binary boxer aliens are attacking New Zealand.'},2500));introTimers.push(setTimeout(()=>{$('introTitle').textContent='YOU ARE OUR BINARY BOXER.';$('introLine').textContent='Decode their numbers. Throw your punches. Save the day!'},5200));introTimers.push(setTimeout(finishIntro,8000));
